import React, { useState } from 'react';

const initial = { name:'', company_name:'', email:'', phone:'', state:'', work_type:'', interest_area:'Product support', wants_follow_up:false, consent:false, notes:'' };
const interests = ['Product support','Training','Contractor discounts','Lead opportunities','Branded planner','Technical troubleshooting','Sales help','Other'];

export default function XPSEpoxyLeadCapture(){
  const [form,setForm]=useState(initial); const [status,setStatus]=useState('idle'); const [error,setError]=useState('');
  const set=(k,v)=>setForm(c=>({...c,[k]:v}));
  async function submit(e){e.preventDefault(); setError(''); if(!form.consent){setError('Consent is required.'); return;} setStatus('sending'); try{const res=await fetch('/api/xps-contractor-success/epoxy-leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); const data=await res.json(); if(!res.ok||!data.ok) throw new Error(data.error||'Lead submission failed.'); setStatus('sent');}catch(err){setError(err.message); setStatus('idle');}}
  return <section className="max-w-7xl mx-auto px-5 pb-12"><form onSubmit={submit} className="rounded-2xl border-[3px] border-[#B8860B] bg-white p-6 md:p-8 shadow-xl"><h2 className="uppercase font-black text-4xl md:text-6xl text-[#050505]">Request XPS Follow-Up</h2><p className="mt-2 text-[#555]">Use this for product support, training, contractor discount interest, lead opportunity interest, branded planner, or technical support interest.</p><div className="mt-6 grid md:grid-cols-2 gap-3">{['name','company_name','email','phone','state','work_type'].map(f=><Field key={f} label={f.split('_').join(' ')} value={form[f]} onChange={v=>set(f,v)} />)}<label><span className="text-xs uppercase tracking-[0.18em] font-black text-[#555]">interest area</span><select value={form.interest_area} onChange={e=>set('interest_area',e.target.value)} className="mt-1 w-full rounded-lg border border-[#d8d8d8] p-3 bg-white">{interests.map(i=><option key={i}>{i}</option>)}</select></label><label className="flex items-center gap-3 mt-6"><input type="checkbox" checked={form.wants_follow_up} onChange={e=>set('wants_follow_up',e.target.checked)} /><span className="font-bold">I want XPS follow-up</span></label></div><textarea value={form.notes} onChange={e=>set('notes',e.target.value)} rows={3} className="mt-3 w-full rounded-lg border border-[#d8d8d8] p-3" placeholder="Notes..."/><label className="mt-4 flex gap-3 text-sm text-[#555]"><input type="checkbox" checked={form.consent} onChange={e=>set('consent',e.target.checked)} /><span>I agree to receive follow-up. I understand program benefits require review and are not automatic.</span></label>{error&&<p className="mt-3 rounded-lg bg-red-50 border border-red-200 text-red-700 p-3 text-sm">{error}</p>}{status==='sent'&&<p className="mt-3 rounded-lg bg-green-50 border border-green-200 text-green-700 p-3 text-sm">Follow-up request received.</p>}<button disabled={status==='sending'} className="mt-5 rounded-full bg-[#050505] text-[#D6A21A] uppercase font-black px-8 py-4">{status==='sending'?'Submitting...':'Submit Follow-Up Request'}</button></form></section>
}
function Field({label,value,onChange}){return <label><span className="text-xs uppercase tracking-[0.18em] font-black text-[#555]">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-[#d8d8d8] p-3" /></label>}
