import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const GROQ_URL = 'https://api.groq.com/openai/v1/chat/completions';
const MODEL = 'llama-3.3-70b-versatile';

async function callGroq(apiKey, system, user) {
  const res = await fetch(GROQ_URL, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: MODEL,
      messages: [{ role: 'system', content: system }, { role: 'user', content: user }],
      max_tokens: 1500,
      temperature: 0.8,
    }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error?.message || 'Groq error');
  return data.choices[0].message.content;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const apiKey = Deno.env.get('GROQ_API_KEY');
    if (!apiKey) return Response.json({ error: 'GROQ_API_KEY not set' }, { status: 500 });

    // Generate 3 random novel business ideas per call
    const ideaPrompt = `You are a brilliant venture capitalist and innovation strategist with deep knowledge across AI, fintech, climate tech, biotech, and consumer tech.

Generate 3 completely novel, viable, and high-potential business ideas that:
1. Solve a real, underserved market need
2. Have clear revenue potential ($10M+ ARR feasible within 5 years)
3. Are technically feasible today
4. Haven't been done exactly this way before
5. Appeal to early adopters or enterprise buyers

For EACH idea provide ONLY these exact fields:
- TITLE: Catchy, memorable name
- DOMAIN: fintech | aitools | climate | biotech | consumer | enterprise | other
- DESCRIPTION: 1-2 sentences on the core problem & solution
- TARGET_MARKET: Who pays? (e.g. "Enterprise SaaS teams", "Climate-conscious SMBs")
- TAM_ESTIMATE: Rough total addressable market in billions
- REVENUE_MODEL: How does it make money? (SaaS, marketplaces, licensing, etc)
- MOAT: What makes it defensible? (network effects, data, patents, etc)

Separate ideas with "---"`;

    const ideas = await callGroq(apiKey,
      'You are a world-class startup idea generator. Output ideas in plain text with clear labels.',
      ideaPrompt
    );

    // Parse and create ideas
    const ideaBlocks = ideas.split('---').filter(b => b.trim());
    const created = [];

    for (const block of ideaBlocks) {
      const text = block.trim();
      
      // Extract fields using regex
      const titleMatch = text.match(/TITLE:\s*([^\n]+)/i);
      const domainMatch = text.match(/DOMAIN:\s*([^\n]+)/i);
      const descMatch = text.match(/DESCRIPTION:\s*([^\n]+)/i);
      const marketMatch = text.match(/TARGET_MARKET:\s*([^\n]+)/i);
      const tamMatch = text.match(/TAM_ESTIMATE:\s*([^\n]+)/i);
      const revenueMatch = text.match(/REVENUE_MODEL:\s*([^\n]+)/i);
      const moatMatch = text.match(/MOAT:\s*([^\n]+)/i);

      const title = (titleMatch?.[1] || '').trim() || 'Novel Business Idea';
      const domain = ((domainMatch?.[1] || 'other').toLowerCase().match(/\w+/)?.[0] || 'other');
      const description = (descMatch?.[1] || '').trim();
      const targetMarket = (marketMatch?.[1] || '').trim();
      const tam = (tamMatch?.[1] || '').trim();
      const revenueModel = (revenueMatch?.[1] || '').trim();
      const moat = (moatMatch?.[1] || '').trim();

      if (!title || title === 'Novel Business Idea') continue;

      const idea = {
        title,
        origin_agent: 'AutoGenerator',
        domain,
        description,
        sources: 'Auto-generated by Groq',
        status: 'seeded',
        iteration: 0,
        tags: [revenueModel, domain].filter(Boolean).join(', '),
        full_concept: text,
        revenue_potential: tam,
        simulation_result: JSON.stringify({ targetMarket, moat, revenueModel }),
      };

      const res = await base44.entities.VisionIdea.create(idea);
      created.push({ id: res.id, title: res.title, status: res.status });
    }

    return Response.json({
      success: true,
      generatedCount: created.length,
      ideas: created,
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});