import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { motion, AnimatePresence } from 'framer-motion';
import { Download, Loader2, Presentation, FileText, CheckCircle2, Copy } from 'lucide-react';

export default function PresentationGenerator({ ideaId, ideaTitle }) {
  const [generating, setGenerating] = useState(false);
  const [deck, setDeck] = useState(null);
  const [includeFinancials, setIncludeFinancials] = useState(true);
  const [copied, setCopied] = useState(false);

  const generate = async () => {
    setGenerating(true);
    try {
      const res = await base44.functions.invoke('generatePitchDeck', { ideaId, includeFinancials });
      if (res.data?.deck) setDeck(res.data.deck);
    } catch (error) {
      console.error('Pitch deck generation failed:', error);
    }
    setGenerating(false);
  };

  const downloadAsText = () => {
    if (!deck) return;
    const text = `
${deck.ideaTitle} — Investor Pitch Deck
Generated: ${new Date(deck.generatedAt).toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXECUTIVE SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${deck.executiveSummary}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PITCH DECK SLIDES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${deck.slides}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Vision Cortex Presentation Engine
Domain: ${deck.domain}
Financials Included: ${includeFinancials ? 'Yes' : 'No'}
`;
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${deck.ideaTitle}-pitch-deck.txt`;
    a.click();
  };

  const copyToClip = () => {
    const text = `${deck.executiveSummary}\n\n${deck.slides}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-4">
      {!deck ? (
        <div className="rounded-2xl border border-border bg-card/50 p-6 space-y-4">
          <div className="flex items-center gap-3 mb-4">
            <Presentation className="w-5 h-5 text-accent" />
            <h3 className="font-display text-lg">Investor Pitch Deck Generator</h3>
          </div>

          <p className="text-sm text-muted-foreground">
            Generate a professional 12-slide investor pitch deck with executive summary, market analysis, financials, and strategic positioning.
          </p>

          <div className="space-y-3">
            <label className="flex items-center gap-3 p-3 rounded-xl border border-border bg-secondary/20 cursor-pointer hover:bg-secondary/40 transition">
              <input type="checkbox" checked={includeFinancials} onChange={e => setIncludeFinancials(e.target.checked)} 
                className="w-4 h-4 rounded" />
              <span className="text-sm">Include 3-year financial projections & CAC analysis</span>
            </label>
          </div>

          <button onClick={generate} disabled={generating || !ideaId}
            className="w-full flex items-center justify-center gap-2 px-6 py-3.5 rounded-xl btn-ivory text-sm disabled:opacity-60">
            {generating ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating…</> : <><Presentation className="w-4 h-4" /> Generate Pitch Deck</>}
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-green-500/30 bg-green-500/5 p-6">
            <div className="flex items-start gap-3 mb-4">
              <CheckCircle2 className="w-5 h-5 text-green-400 flex-shrink-0 mt-0.5" />
              <div>
                <h3 className="font-display text-lg text-green-400 mb-1">Pitch Deck Generated</h3>
                <p className="text-sm text-muted-foreground">{deck.ideaTitle} — 12 slides + executive summary</p>
              </div>
            </div>

            {/* Executive Summary Preview */}
            <div className="mt-5 p-4 rounded-xl border border-green-500/20 bg-card/40">
              <div className="text-xs uppercase tracking-[0.2em] text-green-400 mb-2">Executive Summary</div>
              <p className="text-xs text-foreground/80 line-clamp-4">{deck.executiveSummary}</p>
            </div>

            {/* Slide Preview */}
            <div className="mt-5 p-4 rounded-xl border border-green-500/20 bg-card/40">
              <div className="text-xs uppercase tracking-[0.2em] text-green-400 mb-2">Deck Preview (First 500 chars)</div>
              <pre className="text-[10px] text-muted-foreground overflow-x-auto max-h-40 leading-relaxed">
                {deck.slides.substring(0, 500)}...
              </pre>
            </div>

            {/* Actions */}
            <div className="flex gap-2 mt-5">
              <button onClick={copyToClip}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl border border-accent/30 bg-accent/10 text-accent text-sm hover:bg-accent/20 transition">
                {copied ? <><CheckCircle2 className="w-4 h-4" /> Copied</> : <><Copy className="w-4 h-4" /> Copy to Clipboard</>}
              </button>
              <button onClick={downloadAsText}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl btn-ivory text-sm">
                <Download className="w-4 h-4" /> Download as Text
              </button>
            </div>

            <button onClick={() => setDeck(null)}
              className="w-full mt-3 px-4 py-2.5 rounded-xl border border-border text-sm hover:bg-secondary/40 transition">
              Generate Another
            </button>
          </motion.div>

          {/* Full Deck Expandable */}
          <details className="rounded-2xl border border-border bg-card/50 p-4">
            <summary className="text-sm font-medium cursor-pointer flex items-center gap-2">
              <span>📊 Full Pitch Deck (Click to expand)</span>
            </summary>
            <div className="mt-4 p-4 rounded-xl bg-secondary/20 text-xs text-foreground/80 whitespace-pre-wrap break-words max-h-96 overflow-y-auto font-mono">
              {deck.slides}
            </div>
          </details>
        </div>
      )}
    </div>
  );
}