import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const GROQ_API_KEY = Deno.env.get('GROQ_API_KEY');
const GITHUB_TOKEN = Deno.env.get('GITHUB_TOKEN');

async function analyzeCodeForIssues(code, functionName, projectContext) {
  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${GROQ_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages: [
        {
          role: 'system',
          content: `You are a senior code reviewer. Analyze the provided code for:
1. Performance issues (inefficient loops, N+1 queries, memory leaks)
2. Security vulnerabilities (injection, auth bypasses, data exposure)
3. Maintainability concerns
4. Suggestions for improvement

Provide concise, actionable feedback. Format as:
**Performance Issues:**
- [issues]

**Security Concerns:**
- [concerns]

**Improvements:**
- [suggestions]

If no issues found, respond with "✅ Code looks good!"`,
        },
        {
          role: 'user',
          content: `Review this code:\n\n\`\`\`\n${code}\n\`\`\`\n\nFunction: ${functionName}\nProject context: ${JSON.stringify(projectContext)}`,
        },
      ],
    }),
  });

  const result = await response.json();
  return result.choices[0].message.content;
}

async function postGitHubComment(owner, repo, prNumber, comment) {
  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`,
    {
      method: 'POST',
      headers: {
        'Authorization': `token ${GITHUB_TOKEN}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        body: comment,
      }),
    }
  );

  if (!response.ok) {
    throw new Error(`GitHub API error: ${response.statusText}`);
  }

  return response.json();
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Fetch unreviewed recent CodeOperations
    const recentOps = await base44.entities.CodeOperation.filter(
      { 
        user_email: user.email,
        operation_type: { $in: ['create_file', 'modify_file'] },
        status: 'completed',
      },
      '-timestamp',
      5
    );

    if (recentOps.length === 0) {
      return Response.json({ message: 'No recent operations to review' });
    }

    // Get project context
    const projectIndexes = await base44.entities.ProjectIndex.filter(
      { user_email: user.email },
      '-last_indexed',
      1
    );

    const projectIndex = projectIndexes[0];
    if (!projectIndex) {
      return Response.json({ error: 'Project index not found' }, { status: 400 });
    }

    const [owner, repo] = projectIndex.github_repo_url?.split('/').slice(-2) || [];
    if (!owner || !repo) {
      return Response.json({ error: 'GitHub repo not configured' }, { status: 400 });
    }

    // Process each operation
    const reviews = [];
    for (const op of recentOps) {
      if (!op.content || op.target_path.includes('node_modules')) {
        continue;
      }

      // Analyze code
      const analysis = await analyzeCodeForIssues(
        op.content,
        op.target_path,
        {
          entities: JSON.parse(projectIndex.entity_schemas || '[]').map(e => e.name),
          functions: JSON.parse(projectIndex.function_list || '[]').map(f => f.name),
        }
      );

      // Try to find related PR (assume latest PR matches this commit)
      const prsResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls?state=open&sort=updated&direction=desc&per_page=1`, {
        headers: { 'Authorization': `token ${GITHUB_TOKEN}` },
      });

      if (prsResponse.ok) {
        const prs = await prsResponse.json();
        const pr = prs[0];

        if (pr) {
          // Post comment to PR
          const prComment = `### 🤖 AI Code Review: ${op.target_path}\n\n${analysis}\n\n_Auto-generated by Architecture AI on ${new Date().toLocaleString()}_`;

          await postGitHubComment(owner, repo, pr.number, prComment);

          reviews.push({
            operation_id: op.id,
            pr_number: pr.number,
            file: op.target_path,
            analysis,
          });
        }
      }
    }

    return Response.json({
      success: true,
      reviews_posted: reviews.length,
      reviews,
    });
  } catch (error) {
    console.error('PR monitoring error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});